config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :orders
  resources :products, except: :show
	get '/products/dashboard', to: 'products#dashboard', as: :dashboard
  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
class Box < ApplicationRecord
  has_many :line_items
  accepts_nested_attributes_for :line_items, reject_if: :all_blank, allow_destroy: true
  belongs_to :order
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :box
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :boxes
  accepts_nested_attributes_for :boxes, reject_if: :all_blank, allow_destroy: true

  enum payment_method: { cash: 0, paynow: 1 }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  # belongs_to :box
  has_one :line_item

  has_one_attached :product_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
	  stored_location_for(resource) || root_path
	end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.buyer_details = {
      name: params[:name],
      contact_number: params[:contact_number]
    }
    if @order.save!
      redirect_to products_path, notice: 'Order is submitted successfully.'
    else
      render :new
    end
  end

  private
  def order_params
    params.require(:order).permit(:location, :payment_date, :payment_method, :buyer_details, boxes_attributes: [:id, :_destroy, line_items_attributes: [:id, :_destroy, :product_id, :quantity] ])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: :dashboard
  before_action :set_product, except: [:index, :new, :create, :dashboard]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    @product.image_url = @product.product_image.blob.service_url.sub(/\?.*/, '') if @product.product_image.attached?
    if @product.save!
      redirect_to products_path, notice: 'Product is saved successfully.'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @product.update(product_params)
      redirect_to dashboard_path, notice: 'Product is updated successfully!'
    else
      redirect_to root_path, alert: 'Product is not updated!'
    end
  end

  def destroy
    if @product.destroy
      redirect_to dashboard_path, notice: 'Product successfully deleted'
    else
      redirect_to root_path, alert: 'Product not deleted due to errors'
    end
  end

  def dashboard
    @products = Product.all
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock_count, :user_id, :product_image, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "success" then "ui green message"
    when "error" then "ui red message"
    when "notice" then "ui blue message"
    end
  end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_messages.html.slim
- flash.each do |key, value|
  div class=("alert alert-#{key}") 
    a.close data-dismiss="alert" href="#" class="text-double"  ×
      #{value}

app/views/layouts/_navbar.html.slim
.ui.grid.navbar-grid
  .computer.only.row
    .column
      .ui.black.huge.inverted.menu.border-radius-0
        = link_to "Home", root_path, class: 'item'
        - if user_signed_in?
          = link_to "Products", new_product_path, class: 'item'
          = link_to "Dashboard", dashboard_path, class: 'item'
        - else
          = link_to "FAQ", '#', class: 'item'
        / Log out to root path
        - if user_signed_in?
          .right.menu
            span.item
              i.user.secret.icon
            = link_to "Logout", destroy_user_session_path, method: :delete, class: 'ui item'

  .tablet.mobile.only.row
    .column
      .ui.black.huge.inverted.menu.border-radius-0
        a#mobile_item.item
          i.bars.icon
.ui.pushable
  .ui.sidebar.vertical.menu
    = link_to "Home", root_path, class: 'item'
    - if user_signed_in?
      = link_to("Products", new_product_path, class: 'item')
      = link_to "Dashboard", dashboard_path , class: 'item'
      = link_to "Logout", destroy_user_session_path, method: :delete, class: 'ui item'
    - else
      = link_to "FAQ", '#', class: 'item'
  .pusher
    #content
      - flash.each do |key, value|
        div class=("#{flash_class(key)} closable") 
          i.close.icon
          = value
      = yield

javascript:
  $('.ui.sidebar').sidebar({
      context: $('.ui.pushable'),
      transition: 'overlay'
  }).sidebar('attach events', '#mobile_item');

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, maximum-scale=1, user-scalable=no" name="viewport" /
    title OrderManagementSystem
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navbar'
    / = render 'layouts/messages'
    
    / = yield

app/views/orders/_box_fields.html.slim
.ui.segment
  .nested-fields
    #line_items
      = f.fields_for :line_items do |line_item|
        = render 'line_item_fields', f: line_item
      .links
        = link_to_add_association 'Add product', f, :line_items, class: 'ui right floated tiny green button'
    = link_to_remove_association "Remove box", f, class: 'ui tiny red button'
  .ui.hidden.divider

app/views/orders/_line_item_fields.html.slim
.nested-fields
  .inline.fields
    .field
      = f.label :product_id, 'Product'
      = f.select :product_id, Product.all.collect {|x| [x.name, x.id]}, {include_blank: true}, {class: 'ui fluid search dropdown'}
    .field
      = f.label :quantity, 'Quantity'
      = f.number_field :quantity
    = link_to_remove_association "X", f, class: 'ui tiny red button'

app/views/orders/index.html.slim
h1 Hello.

app/views/orders/new.html.slim
.ui.container.marg-t
  h1.huge Order information
  = form_for @order, html: {class: "ui form"}do |f|
    .ui.segments
      .huge.ui.segment Your details:
      .ui.segments
        .ui.segment
          .field
            = label_tag 'Name'
            = text_field_tag 'name'
        .ui.segment
          .field
            = label_tag 'Contact No.'
            = text_field_tag 'contact_number'
    .ui.segments
      .huge.ui.segment Your preferences:
      .ui.segments
        .ui.segment
          .field
            = f.label :payment_date, 'Payment Date '
            = f.date_field :payment_date
        .ui.segment
          .field
            = f.label :location, 'Meet-Up Location '
            = f.text_field :location
        .ui.segment
          .field
            = f.label :payment_method, 'Payment by '
            = f.select :payment_method, options_for_select([['Cash',
      'cash'],['Paynow','paynow']]),{ include_blank: true }, { class: "ui fluid search dropdown" }
    .ui.segments
      .huge.ui.segment Products:
      .ui.segments
        .ui.segment
          #boxes
            = f.fields_for :boxes do |box|
              = render 'box_fields', f: box
            .links
              = link_to_add_association 'Add box', f, :boxes, class: "ui tiny green button"
    = f.submit 'Submit', data: { confirm: 'Once submitted, no changes. Proceed?' }, class: 'ui blue button'

app/views/products/dashboard.html.slim
.ui.container.marg-t.marg-b
  h2.ui.center.aligned.icon.header
    i.clipboard.icon.circular
    | Products Dashboard
  table.ui.celled.table.unstackable.table-mobile-styling
    thead
      tr
        th.one.wide No.
        th.two.wide Image
        th.six.wide Product
        th.one.wide 
        th.one.wide 
    tbody
      - @products.each_with_index do |p, index|
        tr
          td = index + 1
          td = image_tag p.product_image, class: 'image-dashboard'
          td 
            = p.name
            br
            span.ui.italic = p.description
            br
            = "Price: #{p.price}"
            br
            = "Stock: #{p.stock_count}"
          td 
            = link_to 'Edit', edit_product_path(p.id), class: 'ui small positive button'
          td = link_to 'Delete', product_path(p.id), method: :delete,  data: {confirm: "Are you sure you want to delete #{p.name}?"}, class: 'ui small negative button'
          

app/views/products/edit.html.slim
.ui.container.marg-t
  = form_for @product, html: {class: "ui form"}do |f|
    .field
      = f.label :name, 'Name: '
      = f.text_field :name
    .field
      = f.label :description, 'Description: '
      = f.text_field :description
    .field
      = f.label :price, 'Price: '
      = f.number_field :price, step: 0.01
    .field
      = f.label :stock_count, 'Stock Count: '
      = f.number_field :stock_count
    .field
      = f.label :product_image, 'Image'
      = f.file_field :product_image, disabled: true
    = f.submit 'Submit', class: 'ui blue button'

app/views/products/index.html.slim
.ui.inverted.vertical.masthead.center.aligned.segment.marg-b
  .ui.text.container
    h1.ui.inverted.header Order Management System
    .lower-text
      h4 Check out our product and click the button below to order.
      .order-new
        = link_to 'Order now <i class="right arrow icon"></i>'.html_safe, new_order_path, class: 'ui large primary button'
.ui.cards.three.column.container.stackable.grid
  - @products.each do |prod|
    .card
      .image
        = image_tag(prod.product_image, class: 'card-image') if prod.product_image.present?
      .content.min-h
        a.header = prod.name
        div.meta
          span = prod.description
        .price
          | $
          = prod.price
          

app/views/products/new.html.slim
.ui.container
  = form_for @product, html: {class: "ui form"}do |f|
    .field
      = f.label :name, 'Name: '
      = f.text_field :name
    .field
      = f.label :description, 'Description: '
      = f.text_field :description
    .field
      = f.label :price, 'Price: '
      = f.number_field :price, step: 0.01
    .field
      = f.label :stock_count, 'Stock Count: '
      = f.number_field :stock_count
    .field
      = f.label :product_image, 'Image'
      = f.file_field :product_image
    = f.submit 'Submit', class: 'ui blue button'